#' Write FGDC metadata for a network-allocation GeoPackage
#'
#' Creates a companion XML metadata record using the FGDC Content Standard for
#' Digital Geospatial Metadata (CSDGM). The record describes the published
#' network-allocation layer, its fields, calculation conventions, and the
#' authoritative source datasets used by WaterRAT.
#'
#' @param network_allocation An `sf` network-allocation result.
#' @param path Path for the XML metadata file.
#' @param gpkg_path Path to the companion GeoPackage, when available.
#' @param layer GeoPackage layer name.
#' @return `path`, invisibly. The XML file is written as a sidecar to the
#'   GeoPackage.
#' @export
write_network_allocation_metadata <- function(
    network_allocation,
    path,
    gpkg_path = NA_character_,
    layer = "network_allocation") {
  if (!inherits(network_allocation, "sf")) {
    stop("`network_allocation` must be an sf object.", call. = FALSE)
  }
  if (length(path) != 1L || is.na(path) || !nzchar(path)) {
    stop("`path` must be one non-empty XML file path.", call. = FALSE)
  }

  add_node <- function(parent, name, value = NULL) {
    child <- xml2::xml_add_child(parent, name)
    if (!is.null(value) && length(value) && !is.na(value[[1L]])) {
      xml2::xml_set_text(child, as.character(value[[1L]]))
    }
    child
  }
  add_citation <- function(parent, title, url = NULL, element = "citation") {
    citation <- add_node(parent, element)
    citeinfo <- add_node(citation, "citeinfo")
    add_node(citeinfo, "origin", "WaterRAT")
    add_node(citeinfo, "pubdate", format(Sys.Date(), "%Y%m%d"))
    add_node(citeinfo, "title", title)
    if (!is.null(url)) add_node(citeinfo, "onlink", url)
    citation
  }

  field_definition <- function(field) {
    definitions <- c(
      comid = "NHDPlus flowline COMID used as the reporting-reach identifier.",
      maug_hist = "FlowMet historical mean August flow for the reporting reach, in cubic feet per second.",
      qe_08 = "NHDPlus August flow-reference attribute joined by COMID."
    )
    if (field %in% names(definitions)) return(unname(definitions[[field]]))
    if (grepl("^intersecting_flow_.*_percent$", field)) {
      base_field <- sub("_percent$", "", field)
      return(paste0(
        "Percentage of maug_hist represented by ", base_field,
        "; calculated as 100 × allocation / maug_hist. NA when maug_hist is missing or zero."
      ))
    }
    if (grepl("^intersecting_flow_", field)) {
      scope <- sub("^intersecting_flow_", "", field)
      return(paste0(
        "Cumulative upstream eligible water-right allocation for ",
        gsub("_", " ", scope), ", in cubic feet per second."
      ))
    }
    paste0("WaterRAT network-allocation attribute: ", field, ".")
  }

  source_records <- list(
    list(
      title = "Montana DNRC Water Rights Query System water-right geodatabase",
      url = "https://opendata-mtdnrc.hub.arcgis.com/maps/edf5bfa459304c3bb8af3361b21e92f2/about"
    ),
    list(
      title = "Idaho Department of Water Resources points of diversion and Water Right Reports",
      url = "https://data-idwr.hub.arcgis.com/datasets/f0b37d653f8249a4945d61bdb98dc4a7_0/explore"
    ),
    list(
      title = "NHDPlus Version 2.1 National Seamless Lower 48 geodatabase",
      url = "https://dmap-data-commons-ow.s3.amazonaws.com/NHDPlusV21/Data/NationalData/NHDPlusV21_NationalData_Seamless_Geodatabase_Lower48_07.7z"
    ),
    list(
      title = "USDA Forest Service hydro flow metrics (FlowMet)",
      url = "https://data.fs.usda.gov/geodata/edw/datasets.php?xmlKeyword=hydro+flow+metric"
    ),
    list(
      title = "USDA Forest Service administrative boundaries and ownership data",
      url = "https://data.fs.usda.gov/geodata/edw/datasets.php?dsetCategory=boundaries"
    )
  )

  bbox_layer <- network_allocation
  if (!is.na(sf::st_crs(network_allocation))) {
    bbox_layer <- sf::st_transform(network_allocation, 4326)
  }
  bbox <- sf::st_bbox(bbox_layer)
  crs_input <- sf::st_crs(network_allocation)$input
  if (is.null(crs_input) || is.na(crs_input) || !nzchar(crs_input)) {
    crs_input <- "Not reported"
  }
  attribute_data <- sf::st_drop_geometry(network_allocation)

  root <- xml2::xml_new_root("metadata")
  idinfo <- add_node(root, "idinfo")
  add_citation(idinfo, "WaterRAT network allocation results", gpkg_path)
  descript <- add_node(idinfo, "descript")
  add_node(descript, "abstract", paste(
    "Flowline-level cumulative water-right allocations generated by WaterRAT.",
    "Eligible state point-of-diversion records are standardized, assigned to NHDPlus COMIDs,",
    "and accumulated downstream through the connected NHDPlus routing network."
  ))
  add_node(descript, "purpose", paste(
    "Support review of cumulative authorized allocations relative to modeled August flow",
    "while retaining separate instream, non-instream, Forest Service, and private totals."
  ))
  timeperd <- add_node(idinfo, "timeperd")
  timeinfo <- add_node(timeperd, "timeinfo")
  add_node(timeinfo, "sngdate") |> add_node("caldate", format(Sys.Date(), "%Y%m%d"))
  add_node(timeperd, "current", "publication date")
  status <- add_node(idinfo, "status")
  add_node(status, "progress", "Complete")
  add_node(status, "update", "As needed")
  spdom <- add_node(idinfo, "spdom")
  bounding <- add_node(spdom, "bounding")
  add_node(bounding, "westbc", bbox[["xmin"]])
  add_node(bounding, "eastbc", bbox[["xmax"]])
  add_node(bounding, "northbc", bbox[["ymax"]])
  add_node(bounding, "southbc", bbox[["ymin"]])
  keywords <- add_node(idinfo, "keywords")
  theme <- add_node(keywords, "theme")
  add_node(theme, "themekt", "None")
  for (keyword in c("water rights", "water allocation", "NHDPlus", "hydrography", "WaterRAT")) {
    add_node(theme, "themekey", keyword)
  }
  add_node(idinfo, "accconst", "None")
  add_node(idinfo, "useconst", paste(
    "Use with the source-data terms and limitations. Allocation totals are screening and review outputs,",
    "not a legal determination of water-right validity, availability, or consumptive use."
  ))

  dataqual <- add_node(root, "dataqual")
  attracc <- add_node(dataqual, "attracc")
  add_node(attracc, "attraccr", "See attribute definitions and source datasets.")
  lineage <- add_node(dataqual, "lineage")
  for (source in source_records) {
    srcinfo <- add_node(lineage, "srcinfo")
    add_citation(srcinfo, source$title, source$url, element = "srccite")
    add_node(srcinfo, "typesrc", "Digital vector data")
  }
  procstep <- add_node(lineage, "procstep")
  add_node(procstep, "procdesc", paste(
    "WaterRAT filters source records to eligible surface-water rights, standardizes state fields,",
    "assigns each POD to an NHDPlus COMID, classifies Forest Service intersection, aggregates local",
    "allocation measures, and propagates them downstream along NHDPlus routing edges. Results are",
    "joined to FlowMet maug_hist and NHDPlus qe_08 by COMID."
  ))
  add_node(procstep, "procdate", format(Sys.Date(), "%Y%m%d"))

  spdoinfo <- add_node(root, "spdoinfo")
  add_node(spdoinfo, "direct", "Vector")
  ptvctinf <- add_node(spdoinfo, "ptvctinf")
  sdtsterm <- add_node(ptvctinf, "sdtsterm")
  add_node(sdtsterm, "sdtstype", "String")
  ptvctcnt <- add_node(ptvctinf, "ptvctcnt")
  esriterm <- add_node(ptvctcnt, "esriterm")
  add_node(esriterm, "efeageom", "Polyline")
  add_node(esriterm, "efeacnt", nrow(network_allocation))

  spref <- add_node(root, "spref")
  horizsys <- add_node(spref, "horizsys")
  geograph <- add_node(horizsys, "geograph")
  add_node(geograph, "geogunit", "Decimal degrees")
  geodetic <- add_node(horizsys, "geodetic")
  add_node(geodetic, "horizdn", crs_input)

  eainfo <- add_node(root, "eainfo")
  detailed <- add_node(eainfo, "detailed")
  enttyp <- add_node(detailed, "enttyp")
  add_node(enttyp, "enttypl", layer)
  add_node(enttyp, "enttypd", "WaterRAT reportable NHDPlus flowlines with cumulative allocations.")
  for (field in names(attribute_data)) {
    attr <- add_node(detailed, "attr")
    add_node(attr, "attrlabl", field)
    add_node(attr, "attrdef", field_definition(field))
    add_node(attr, "attrdefs", "WaterRAT output data contract")
    domain <- add_node(attr, "attrdomv")
    if (is.numeric(attribute_data[[field]])) {
      add_node(domain, "rdom", "Numeric value; units are specified in the attribute definition.")
    } else {
      add_node(domain, "udom", "See attribute definition.")
    }
  }
  metainfo <- add_node(root, "metainfo")
  add_node(metainfo, "metd", format(Sys.Date(), "%Y%m%d"))
  add_node(metainfo, "metc", "WaterRAT package")
  add_node(metainfo, "metstdn", "Content Standard for Digital Geospatial Metadata (CSDGM)")
  add_node(metainfo, "metstdv", "FGDC-STD-001-1998")

  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  xml2::write_xml(root, path, options = "format")
  invisible(path)
}
